# -*- coding: utf-8 -*-
"""Multimodal_UnetAttention_Model.ipynb

Automatically generated by Colab.

"""

from google.colab import drive
drive.mount('/content/drive')

hdf5_path = './drive/MyDrive/gsgm_dataset_DEMO/train.hdf5'

import numpy as np
import h5py
from skimage.restoration import denoise_nl_means, estimate_sigma
from sklearn.model_selection import train_test_split
from typing import Tuple, Dict, List

with h5py.File(hdf5_path, 'r') as f:
    region = f['ALP-15-13']
    for k in region.keys():
        if k == 'outlines':
            continue
        arr = np.array(region[k])
        print(k, arr.shape)

with h5py.File(hdf5_path, 'r') as f:
  store = list(f.keys())
  print(len(store))

import h5py
import numpy as np
from typing import Tuple, List, Optional
from sklearn.model_selection import train_test_split
from skimage.restoration import denoise_nl_means, estimate_sigma  # [web:1][web:19]


# ---------- Utility Functions --------------

def normalize_image(image: np.ndarray) -> np.ndarray:
    """
    Normalize an image array to the range [0, 1] using min-max scaling.
    """
    x = image.astype(np.float32)
    x_min = np.min(x)
    x_max = np.max(x)
    denom = x_max - x_min + 1e-8
    normalized = (x - x_min) / denom
    return normalized


# --------- Denoising Functions -------------

def denoise_nlm_multichannel(img: np.ndarray, strength: float = 0.8) -> np.ndarray:
    """
    Apply Non-Local Means denoising to each channel of a multichannel image.
    """
    if img.ndim != 3:
        raise ValueError(
            f"Expected a 3D array (H, W, C), but got shape {img.shape}."
        )

    denoised_channels = []

    for c in range(img.shape[-1]):
        channel = img[..., c]
        sigma = np.mean(estimate_sigma(channel, channel_axis=None))
        h = strength * sigma

        denoised_channel = denoise_nl_means(
            channel,
            h=h,
            patch_size=5,
            patch_distance=6,
            fast_mode=True,
            channel_axis=None
        )
        denoised_channels.append(denoised_channel)

    denoised_img = np.stack(denoised_channels, axis=-1)

    if np.issubdtype(img.dtype, np.integer):
        info = np.iinfo(img.dtype)
        denoised_img = np.clip(denoised_img, info.min, info.max).astype(img.dtype)
    else:
        denoised_img = denoised_img.astype(img.dtype, copy=False)

    return denoised_img


# --------- Multimodal HDF5 Processing -------------

def process_hdf5_dataset(
    hdf5_path: str,
    patch_size: int = 128,
    apply_denoise: bool = True,
    min_mask_pixels: int = 10,
    max_regions: Optional[int] = 30,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Process multimodal glacier monitoring HDF5 dataset into patches for training.

    Uses per-region native spatial size (no hard-coded size).
    Can optionally limit to the first `max_regions` regions to save RAM.
    """

    # ORDER CRITICAL – must match what the model expects
    modalities = {
        "co_pol_sar": 2,
        "cross_pol_sar": 2,
        "dem": 2,
        "in_sar": 2,
        "optical": 6
    }

    TOTAL_CHANNELS = sum(modalities.values())

    X_patches: List[np.ndarray] = []
    Y_masks: List[np.ndarray] = []
    region_count = 0
    processed_regions = 0

    print(
        f"🚀 Processing {hdf5_path} | Patch size: {patch_size} | "
        f"Channels: {TOTAL_CHANNELS} | max_regions={max_regions}"
    )

    with h5py.File(hdf5_path, 'r') as f:
        region_keys = list(f.keys())
        if max_regions is not None:
            region_keys = region_keys[:max_regions]

        for region_key in region_keys:
            region = f[region_key]

            # Require outlines
            if "outlines" not in region:
                print(f"⚠️  Skipping {region_key} (no outlines)")
                continue

            print(f"📊 Processing region {region_key}...")
            processed_regions += 1

            # ----- Load mask and infer region size -----
            raw_mask = np.array(region["outlines"], dtype=np.float32)
            if raw_mask.ndim == 3:
                raw_mask = np.argmax(raw_mask, axis=-1)
            binary_mask = (raw_mask > 0).astype(np.float32)

            region_height, region_width = binary_mask.shape

            # Allocate sample tensor using region-native size
            sample = np.zeros((region_height, region_width, TOTAL_CHANNELS), dtype=np.float32)

            # ----- Fill modalities -----
            channel_offset = 0
            for modality_name, num_channels in modalities.items():
                if modality_name in region:
                    raw_data = np.array(region[modality_name], dtype=np.float32)

                    # Handle (C,H,W) → (H,W,C) if stored as (channels, height, width)
                    if raw_data.ndim == 3 and raw_data.shape[0] == num_channels:
                        raw_data = np.transpose(raw_data, (1, 2, 0))

                    # Sanity check spatial size
                    if raw_data.shape[0] != region_height or raw_data.shape[1] != region_width:
                        raise ValueError(
                            f"Spatial mismatch in region '{region_key}', modality '{modality_name}': "
                            f"expected ({region_height},{region_width}), got {raw_data.shape[:2]}"
                        )

                    # Sanity check channel count
                    if raw_data.shape[-1] != num_channels:
                        raise ValueError(
                            f"Channel mismatch in region '{region_key}', modality '{modality_name}': "
                            f"expected {num_channels} channels, got {raw_data.shape[-1]} "
                            f"(shape {raw_data.shape}). Update 'modalities' config."
                        )

                    normalized_data = normalize_image(raw_data)

                    if apply_denoise:
                        if modality_name == "in_sar":
                            normalized_data = denoise_nlm_multichannel(normalized_data, strength=0.8)
                        elif modality_name in ["co_pol_sar", "cross_pol_sar"]:
                            normalized_data = denoise_nlm_multichannel(normalized_data, strength=0.6)
                        # DEM & optical left as-is

                    sample[..., channel_offset:channel_offset + num_channels] = normalized_data
                    # Keep per-modality prints compact
                    print(f"   {modality_name}: {raw_data.shape} → OK")
                else:
                    print(f"   {modality_name}: MISSING (zero-filled)")

                channel_offset += num_channels

            # ----- Patch extraction -----
            patches_extracted = 0

            for i in range(0, region_height - patch_size + 1, patch_size // 2):  # 50% overlap
                for j in range(0, region_width - patch_size + 1, patch_size // 2):
                    img_patch = sample[i:i+patch_size, j:j+patch_size, :]
                    mask_patch = binary_mask[i:i+patch_size, j:j+patch_size]

                    glacier_pixels = np.sum(mask_patch)
                    if glacier_pixels < min_mask_pixels:
                        continue

                    X_patches.append(img_patch)
                    Y_masks.append(mask_patch[..., np.newaxis])
                    patches_extracted += 1

            if patches_extracted > 0:
                region_count += 1
                print(f"  {patches_extracted} valid patches (min_pixels={min_mask_pixels})")
            else:
                print(f"  No patches kept from region {region_key}")

    if not X_patches:
        raise ValueError(
            f"No valid patches extracted! "
            f"Check min_mask_pixels and data (processed_regions={processed_regions})."
        )

    X_train = np.stack(X_patches, axis=0).astype(np.float32)
    Y_train = np.stack(Y_masks, axis=0).astype(np.float32)

    print("\n" + "="*60)
    print("Dataset creation COMPLETE")
    print(f"{len(X_train)} patches from {region_count} regions "
          f"(processed {processed_regions} regions max)")
    print(f"Shapes → X: {X_train.shape} | Y: {Y_train.shape}")
    print(f"Memory: X={X_train.nbytes/1e9:.2f}GB, Y={Y_train.nbytes/1e9:.2f}GB")
    print("="*60)

    return X_train, Y_train


# --------- Data Splitting -------------

def split_glacier_dataset(
    X: np.ndarray,
    Y: np.ndarray,
    train_size: float = 0.7,
    val_size: float = 0.15,
    test_size: float = 0.15,
    random_state: int = 42,
    stratify: bool = True
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Split multimodal glacier dataset into train/val/test sets.
    """

    assert X.shape[0] == Y.shape[0], "X and Y must have same number of samples"
    total_samples = X.shape[0]

    print(f" Splitting {total_samples} patches...")

    if stratify:
        glacier_ratios = np.mean(Y.reshape(total_samples, -1), axis=1)
        print(f" Glacier ratios: {glacier_ratios.min():.1%} - "
              f"{glacier_ratios.mean():.1%} - {glacier_ratios.max():.1%}")

        temp_size = 1.0 - train_size
        X_train, X_temp, Y_train, Y_temp = train_test_split(
            X, Y,
            test_size=temp_size,
            random_state=random_state,
            shuffle=True
        )

        X_val, X_test, Y_val, Y_test = train_test_split(
            X_temp, Y_temp,
            test_size=0.5,
            random_state=random_state,
            shuffle=True
        )
    else:
        X_temp, X_test, Y_temp, Y_test = train_test_split(
            X, Y, test_size=test_size, random_state=random_state, shuffle=True
        )
        X_train, X_val, Y_train, Y_val = train_test_split(
            X_temp, Y_temp,
            test_size=val_size / (train_size + val_size),
            random_state=random_state,
            shuffle=True
        )

    def glacier_stats(masks: np.ndarray) -> str:
        ratios = np.mean(masks.reshape(masks.shape[0], -1), axis=1)
        return f"N={len(masks)} | Glacier: {np.mean(ratios):.1%} ± {np.std(ratios):.1%}"

    print("\n" + "="*70)
    print("DATA SPLIT COMPLETE")
    print("="*70)
    print(f"{'Split':<8} {'Shape':<20} {'Samples':<8} {'Glacier Coverage'}")
    print("-"*70)
    print(f"{'Train':<8} {str(X_train.shape):<20} {len(X_train):<8} {glacier_stats(Y_train)}")
    print(f"{'Val':<8}   {str(X_val.shape):<20} {len(X_val):<8} {glacier_stats(Y_val)}")
    print(f"{'Test':<8}  {str(X_test.shape):<20} {len(X_test):<8} {glacier_stats(Y_test)}")
    print("-"*70)
    print(f"Total: {total_samples} → {len(X_train)}/{len(X_val)}/{len(X_test)}")

    mem_gb = lambda arr: f"{arr.nbytes/1e9:.2f}GB"
    print(f"\n Memory → Train: {mem_gb(X_train):>8}, "
          f"Val: {mem_gb(X_val):>8}, Test: {mem_gb(X_test):>8}")

    return X_train, X_val, X_test, Y_train, Y_val, Y_test


# --------- Usage -------------

X, Y = process_hdf5_dataset(
    hdf5_path,
    patch_size=128,
    apply_denoise=True,
    min_mask_pixels=10,
    max_regions=25,        # limit to first 25 regions
)

X_train, X_val, X_test, Y_train, Y_val, Y_test = split_glacier_dataset(
    X, Y,
    train_size=0.7,
    val_size=0.15,
    test_size=0.15,
    random_state=42,
    stratify=True
)

import h5py
import numpy as np

# After you already have these in RAM:
# X_train, X_val, X_test, Y_train, Y_val, Y_test

save_path = "./drive/MyDrive/gsgm_splits_128.h5"

with h5py.File(save_path, "w") as f:
    # Use gzip compression + chunking for large arrays
    f.create_dataset(
        "X_train",
        data=X_train,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )
    f.create_dataset(
        "Y_train",
        data=Y_train,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )
    f.create_dataset(
        "X_val",
        data=X_val,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )
    f.create_dataset(
        "Y_val",
        data=Y_val,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )
    f.create_dataset(
        "X_test",
        data=X_test,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )
    f.create_dataset(
        "Y_test",
        data=Y_test,
        compression="gzip",
        compression_opts=4,
        chunks=True
    )

print("Saved splits to:", save_path)

load_path = "./drive/MyDrive/gsgm_splits_128.h5"

with h5py.File(load_path, "r") as f:
    X_train = f["X_train"][:]   # shape (547, 128, 128, 17)
    Y_train = f["Y_train"][:]   # shape (547, 128, 128, 1)
    X_val   = f["X_val"][:]     # shape (117, 128, 128, 17)
    Y_val   = f["Y_val"][:]     # shape (117, 128, 128, 1)
    X_test  = f["X_test"][:]    # shape (118, 128, 128, 17)
    Y_test  = f["Y_test"][:]    # shape (118, 128, 128, 1)

print("Loaded shapes:")
print("Train:", X_train.shape, Y_train.shape)
print("Val  :", X_val.shape,   Y_val.shape)
print("Test :", X_test.shape,  Y_test.shape)

# !pip install segmentation-models-pytorch

# ============================
# Imports
# ============================
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
torch.backends.mkldnn.enabled = (DEVICE == "cpu")

class GlacierDataset(Dataset):
    def __init__(self, X, Y):
        self.X = np.ascontiguousarray(X.astype(np.float32))
        self.Y = np.ascontiguousarray(Y.astype(np.float32))

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        img = torch.from_numpy(self.X[idx]).permute(2, 0, 1)   # (C,H,W)
        mask = torch.from_numpy(self.Y[idx]).permute(2, 0, 1)
        return img, mask

# --------- Model -------------

def make_strong_unet(in_channels):
    """
    Multimodal-ready U-Net with SCSE attention.
    ImageNet weights are DISABLED because input channels != 3.
    """
    model = smp.Unet(
        encoder_name="resnet34",
        encoder_weights=None,          # MUST be None for 16-channel input
        in_channels=in_channels,       # e.g., 16
        classes=1,
        activation=None,
        decoder_attention_type="scse",
        encoder_depth=5,
        decoder_channels=[256,128,64,32,16]
    )
    return model.to(DEVICE)

# ------------ Loss Functions --------------

class DiceLoss(nn.Module):
    def __init__(self, smooth=1e-6):
        super().__init__()
        self.smooth = smooth

    def forward(self, logits, targets):
        probs = torch.sigmoid(logits)
        dims = (2, 3)
        intersection = (probs * targets).sum(dim=dims)
        denominator = probs.sum(dim=dims) + targets.sum(dim=dims)
        dice = (2 * intersection + self.smooth) / (denominator + self.smooth)
        return 1 - dice.mean()


bce = nn.BCEWithLogitsLoss()
dice = DiceLoss()

def combo_loss(logits, targets, alpha=0.5):
    return alpha * bce(logits, targets) + (1 - alpha) * dice(logits, targets)


# --------------- Metrics -----------------

def binarize(probs, threshold):
    return (probs >= threshold).float()

def dice_score(preds, targets, eps=1e-6):
    dims = (2,3)
    inter = (preds * targets).sum(dim=dims)
    denom = preds.sum(dim=dims) + targets.sum(dim=dims)
    return ((2*inter + eps) / (denom + eps)).mean().item()

def iou_score(preds, targets, eps=1e-6):
    dims = (2,3)
    inter = (preds * targets).sum(dim=dims)
    union = preds.sum(dim=dims) + targets.sum(dim=dims) - inter
    return ((inter + eps) / (union + eps)).mean().item()

def pixel_accuracy(preds, targets):
    return (preds == targets).float().mean().item()

# --------------- Training Validation -----------------

@torch.no_grad()
def validate_model_on_thresholds(model, validation_loader, thresholds=np.linspace(0.3, 0.7, 9)):
    model.eval()

    best_threshold = 0.5
    best_dice = -1
    best_iou = 0
    best_acc = 0

    for threshold in thresholds:
        dice_scores, iou_scores, acc_scores = [], [], []

        for images, masks in validation_loader:
            images, masks = images.to(DEVICE), masks.to(DEVICE)
            probs = torch.sigmoid(model(images))
            preds = binarize(probs, threshold)

            dice_scores.append(dice_score(preds, masks))
            iou_scores.append(iou_score(preds, masks))
            acc_scores.append(pixel_accuracy(preds, masks))

        if np.mean(dice_scores) > best_dice:
            best_dice = np.mean(dice_scores)
            best_iou = np.mean(iou_scores)
            best_acc = np.mean(acc_scores)
            best_threshold = threshold

    return best_threshold, {"dice": best_dice, "iou": best_iou, "acc": best_acc}

from typing import Dict, Any, Tuple
import time

def train_unet_model(
    train_loader: DataLoader,
    val_loader: DataLoader,
    input_channels: int,
    num_epochs: int = 150,
    learning_rate: float = 1e-4,
    weight_decay: float = 1e-4,
    validate_every: int = 3,
    best_model_save_path: str = "unet_best_glacier.pth",
    patience: int = 7,
    min_delta: float = 1e-4,
    device: str = None
) -> Dict[str, Any]:
    device = torch.device(device if device else "cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on {device}")

    model = make_strong_unet(input_channels).to(device)
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Model: {trainable_params/1e6:.1f}M params")

    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay, betas=(0.9, 0.999), eps=1e-8)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs, eta_min=learning_rate * 0.1)

    best_val_dice = -1.0
    best_threshold = 0.5
    no_improve = 0
    train_losses = []
    val_dices = []
    start_time_total = time.time()

    print("\n" + "="*80)
    print("Epoch | Train Loss | LR      | Val Dice | IoU  | Acc  | Threshold | Status")
    print("="*80)

    for epoch in range(1, num_epochs + 1):
        model.train()
        epoch_loss = 0.0
        num_batches = 0
        epoch_start = time.time()

        for batch_idx, (images, masks) in enumerate(train_loader):
            images, masks = images.to(device, non_blocking=True), masks.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)
            outputs = model(images)
            loss = combo_loss(outputs, masks)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            num_batches += 1

            if num_batches % 10 == 0:
                print(f"\rEpoch {epoch:02d}: [{batch_idx+1}/{len(train_loader)}] Loss: {loss.item():.4f}", end="", flush=True)

        train_loss_avg = epoch_loss / num_batches
        train_losses.append(train_loss_avg)
        scheduler.step()
        torch.cuda.empty_cache()
        train_time = time.time() - epoch_start

        if epoch % validate_every == 0 or epoch == num_epochs:
            threshold, val_stats = validate_model_on_thresholds(model, val_loader)
            val_dice = val_stats["dice"]
            val_iou = val_stats["iou"]
            val_acc = val_stats["acc"]
            val_dices.append(val_dice)

            lr = optimizer.param_groups[0]['lr']
            status = " BEST" if val_dice > best_val_dice + min_delta else "CONTINUE"

            print(f"\n{epoch:02d} | {train_loss_avg:.4f} | {lr:.2e} | "
                  f"{val_dice:.3f} | {val_iou:.3f} | {val_acc:.3f} | "
                  f"{threshold:.3f} | {status} ({train_time:.0f}s)")

            if val_dice > best_val_dice + min_delta:
                best_val_dice = val_dice
                best_threshold = threshold
                best_stats = val_stats.copy()

                torch.save({
                    'epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'best_threshold': best_threshold,
                    'val_dice': best_val_dice,
                    'scheduler_state_dict': scheduler.state_dict()
                }, best_model_save_path)

                no_improve = 0
                print(f"  Saved new best model: Dice={val_dice:.4f}")
            else:
                no_improve += 1

        if no_improve >= patience:
            print(f"\nEarly stopping at epoch {epoch}")
            break

    total_time = time.time() - start_time_total

    print("\n" + "="*80)
    print("TRAINING COMPLETE")
    print("="*80)
    print(f"Best Validation Dice: {best_val_dice:.4f} @ threshold {best_threshold:.3f}")
    print(f"Final model saved: {best_model_save_path}")
    print(f"Total training time: {total_time:.0f}s")

    return {
        'best_model_path': best_model_save_path,
        'best_dice': best_val_dice,
        'best_threshold': best_threshold,
        'best_stats': best_stats,
        'train_losses': train_losses,
        'val_dices': val_dices,
        'final_lr': lr,
        'total_time': total_time
    }

# -----------------------------
# Testing / Evaluation
# -----------------------------
import torch
import numpy as np
import io

@torch.no_grad()
def test_model(ckpt_path, test_loader, in_channels):
    # Handle both file path and loaded dict
    if isinstance(ckpt_path, (str, io.BytesIO)):
        checkpoint = torch.load(ckpt_path, map_location=DEVICE, weights_only=False)  
    else:
        checkpoint = ckpt_path

    # Get threshold from results dict or checkpoint
    if 'best_model_path' in checkpoint:
        model_path = checkpoint['best_model_path']
        print(f"Loading model from: {model_path}")
        checkpoint = torch.load(model_path, map_location=DEVICE, weights_only=False)  

    best_threshold = checkpoint.get("best_threshold") or checkpoint.get("threshold", 0.5)

    model = make_strong_unet(in_channels).to(DEVICE)

    # Find state_dict key
    state_dict_key = None
    for key in ["state_dict", "model_state_dict"]:
        if key in checkpoint:
            state_dict_key = key
            break

    if state_dict_key is None:
        raise KeyError(f"No state_dict found. Checkpoint keys: {list(checkpoint.keys())}")

    model.load_state_dict(checkpoint[state_dict_key])
    model.eval()

    dices, ious, accs = [], [], []

    for imgs, masks in test_loader:
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        logits = model(imgs)
        probs = torch.sigmoid(logits)
        preds = binarize(probs, best_threshold)

        dices.append(dice_score(preds, masks))
        ious.append(iou_score(preds, masks))
        accs.append(pixel_accuracy(preds, masks))

    print(f" Dice: {np.mean(dices):.3f} ± {np.std(dices):.3f}")
    print(f" IoU:  {np.mean(ious):.3f} ± {np.std(ious):.3f}")
    print(f"  Acc:  {np.mean(accs):.3f} ± {np.std(accs):.3f}")

    return {
        "dice": np.mean(dices), "iou": np.mean(ious), "accuracy": np.mean(accs),
        "dice_std": np.std(dices), "iou_std": np.std(ious), "acc_std": np.std(accs),
        "overall_dice": dices,
        "overall_ious": ious
    }

train_dataset = GlacierDataset(X_train, Y_train)
val_dataset   = GlacierDataset(X_val, Y_val)
test_dataset  = GlacierDataset(X_test, Y_test)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=16, shuffle=False)
test_loader  = DataLoader(test_dataset, batch_size=8, shuffle=False)

in_channels = X_train.shape[-1]   # = 16 for multimodal

checkpoint_path = train_unet_model(
    train_loader,
    val_loader,
    input_channels=in_channels,
    num_epochs=10
)

test_model(checkpoint_path, test_loader, in_channels)

"""## Training and validation Loss Curve:
Why this is important:-
1. Shows the model converged
2. No overfitting
3. Stable training


What to show:-
1. Training loss vs epochs
2. Validation dice vs epochs


### Results as per the graph:-
The loss decreases smoothly and the validation Dice stabilizes near 0.99, indicating strong generalization.
"""

import matplotlib.pyplot as plt
import numpy as np

def plot_training_curves(results):
    """
    Plot training loss and validation Dice curves from training results.

    Args:
        results: Dict returned from train_unet_model()
    """
    train_losses = results['train_losses']
    val_dices = results['val_dices']

    # Align epochs for plotting
    train_epochs = range(1, len(train_losses) + 1)
    val_epochs = np.array([i for i, _ in enumerate(train_losses) if i % 3 == 0]) + 1  # Every 3rd epoch

    plt.figure(figsize=(12, 5))

    # Training Loss
    plt.subplot(1, 2, 1)
    plt.plot(train_epochs, train_losses, 'b-o', linewidth=2, markersize=6, label='Train Loss')
    plt.title('Training Loss', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Loss', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.ylim(0, max(train_losses) * 1.1)

    # Validation Dice
    plt.subplot(1, 2, 2)
    plt.plot(val_epochs, val_dices, 'r-o', linewidth=3, markersize=8, label='Val Dice')
    plt.axhline(y=results['best_dice'], color='green', linestyle='--', alpha=0.7,
                label=f'Best: {results["best_dice"]:.3f}')
    plt.title('Validation Dice Score', fontsize=14, fontweight='bold')
    plt.xlabel('Epoch', fontsize=12)
    plt.ylabel('Dice Score', fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.ylim(0, 1)

    plt.tight_layout()
    plt.show()

    # Print summary stats
    print("\n" + "="*50)
    print("TRAINING SUMMARY")
    print("="*50)
    print(f"Best Val Dice: {results['best_dice']:.4f}")
    print(f"Best Threshold: {results['best_threshold']:.3f}")
    print(f"Total Epochs: {len(train_losses)}")
    print(f"Final Train Loss: {train_losses[-1]:.4f}")
    print("="*50)

# graph plot
plot_training_curves(checkpoint_path)

"""## Visualize predictions:
The model captures glacier boundaries accurately across different terrain conditions.
"""

def visualize_predictions(model, dataset, idx_list, threshold):
    model.eval()

    for idx in idx_list:
        img, gt = dataset[idx]
        img = img.unsqueeze(0).to(DEVICE)

        with torch.no_grad():
            pred = torch.sigmoid(model(img))
            pred = (pred >= threshold).float()

        img_np = img.cpu().numpy()[0, 0]   # show 1st channel for visualization
        gt_np = gt.numpy()[0]
        pred_np = pred.cpu().numpy()[0,0]

        plt.figure(figsize=(12,3))

        plt.subplot(1,4,1)
        plt.title("Input Image")
        plt.imshow(img_np, cmap="gray")
        plt.axis("off")

        plt.subplot(1,4,2)
        plt.title("Ground Truth")
        plt.imshow(gt_np, cmap="gray")
        plt.axis("off")

        plt.subplot(1,4,3)
        plt.title("Prediction")
        plt.imshow(pred_np, cmap="gray")
        plt.axis("off")

        plt.subplot(1,4,4)
        plt.title("Overlay")
        plt.imshow(img_np, cmap="gray")
        plt.imshow(pred_np, alpha=0.4, cmap="jet")
        plt.axis("off")

        plt.show()



create_dataset = GlacierDataset(X_test, Y_test)
model_path = checkpoint_path["best_model_path"]
best_threshold = checkpoint_path.get("threshold", 0.5)

checkpoint = torch.load(model_path, map_location=DEVICE, weights_only=False)
print(checkpoint.keys())


in_channels = X_test.shape[-1]  # = 17 in your case

model = make_strong_unet(in_channels)
model.load_state_dict(checkpoint["model_state_dict"])
model.to(DEVICE)
model.eval()

# choose any valid indices
idx_list = [2, 11, 12, 13]

# invoke the function
visualize_predictions(model=model, dataset=create_dataset, idx_list=idx_list,
    threshold=best_threshold
)

"""### Error map (Where the model fails)
Why this is powerful ?
1. Shows exact failure regions
2. Helps justify HUAL needs

What to compute ?
1. False positives
2. False negatives

Think of this image as a map of your model's mistakes.

-> Left: False Positives
These are places where the model said "there is glacier" but in reality there is no glacier.

** Interpretation:
1. Over segmentation
2. Often happens on shadows, rock, water or noisy SAR backscatter.

-> Middle: False Negatives
These are places where the model said "no glacier" but in reality there is glacier.

** Interpretation:
1. Under segmentation
2. Often happens on Debris-covered ice, Thin/low-contrast glacier

-> Right: Error Overlay (with color bar)
This combines both error types on one image:

Red areas = false positives (model added glacier wrongly)

Blue areas = false negatives (model missed real glacier)

White/neutral background = pixels the model got correct

"""

def visualize_error_maps(model, dataset, idx_list, threshold):
    model.eval()

    for idx in idx_list:
        img, gt = dataset[idx]
        img = img.unsqueeze(0).to(DEVICE)

        with torch.no_grad():
            pred = torch.sigmoid(model(img))
            pred = (pred >= threshold).float()

        gt_np = gt.numpy()[0]
        pred_np = pred.cpu().numpy()[0,0]
        error = pred_np - gt_np

        plt.figure(figsize=(10,3))
        plt.suptitle(f"Sample {idx}")

        plt.subplot(1,3,1)
        plt.title("False Positives")
        plt.imshow(error == 1, cmap="Reds")
        plt.axis("off")

        plt.subplot(1,3,2)
        plt.title("False Negatives")
        plt.imshow(error == -1, cmap="Blues")
        plt.axis("off")

        plt.subplot(1,3,3)
        plt.title("Error Overlay")
        plt.imshow(error, cmap="bwr")
        plt.colorbar()
        plt.axis("off")

        plt.show()


idx_list = [2, 11, 12, 13]

# invoking the function visualize_error_map
visualize_error_maps(model=model, dataset=create_dataset, idx_list=idx_list, threshold=best_threshold)

# The majority of test samples achieve Dice scores above 0.97, indicating stable performance

def plot_metric_distribution(dices, ious):
    plt.figure(figsize=(10,4))

    plt.subplot(1,2,1)
    plt.hist(dices, bins=20)
    plt.title("Dice Score Distribution")
    plt.xlabel("Dice")
    plt.ylabel("Count")

    plt.subplot(1,2,2)
    plt.hist(ious, bins=20)
    plt.title("IoU Score Distribution")
    plt.xlabel("IoU")
    plt.ylabel("Count")

    plt.tight_layout()
    plt.show()

test_result = test_model(checkpoint_path, test_loader, in_channels)
dices, ious = test_result["overall_dice"], test_result["overall_ious"]

# invoking the plot between dices vs ious
plot_metric_distribution(dices, ious)

