# -*- coding: utf-8 -*-
"""Unet_BaseLine_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvF3SMeS8rhzqT-6o0-1d9Lmx0Ft8J03
"""

from google.colab import drive
drive.mount('/content/drive')

hdf5_path = './drive/MyDrive/gsgm_dataset_DEMO/train.hdf5'

# !pip install tensorflow

# !pip install h5py

# HDF5 -> Hierarical Data Format Version 5
import h5py
store_data = None

with h5py.File(hdf5_path, 'r') as f:
    store_data = list(f.keys())

# All folders present
print(store_data)

new_file = file = h5py.File(hdf5_path, 'r')
dataset_name = store_data[0]
dataset_name

data = new_file[dataset_name]
print(data.keys())

insar_data_ALP = data["in_sar"]
# print(insar_data_ALP[:])

import matplotlib.pyplot as plt

# Channel 1
plt.imshow(insar_data_ALP[:, :, 0], cmap='gray')
plt.title('InSAR Channel 1')
plt.axis('off')
plt.show()

# Channel 2
plt.imshow(insar_data_ALP[:, :, 1], cmap='gray')
plt.title('InSAR Channel 2')
plt.axis('off')
plt.show()

# optical_ALP = data["optical"]
# print(optical_ALP[:])

# import numpy as np
# np.array(data["optical"])

# optical_ALP.shape

# # satellites takes images in multiple channels (distinct wavelength ranges)
# # to highlight features such as vegetation, soil, snow/ice to support scientific analysis

# for i in range(6):
#     plt.imshow(optical_ALP[:, :, i], cmap='gray')
#     plt.title(f'Optical Band {i+1}')
#     plt.axis('off')
#     plt.show()

outline_ALP = data["outlines"]
print(outline_ALP[:].shape)

# Channel 1
plt.imshow(outline_ALP[:, :, 0], cmap='gray')
plt.title('Outline Channel 1')
plt.axis('off')
plt.show()

# Channel 2
plt.imshow(outline_ALP[:, :, 1], cmap='gray')
plt.title('Outline Channel 2')
plt.axis('off')
plt.show()

# !pip install scikit-learn

import numpy as np
from sklearn.model_selection import train_test_split

# # perform data pre-preprocessing
# def process_hdf5_dataset(hdf5_path, patch_size=128):
#     """
#     Processes an InSAR HDF5 dataset into small patches for segmentation.
#     Each region must contain 'in_sar' and 'outlines' datasets.

#     Args:
#         hdf5_path (str): Path to the HDF5 dataset.
#         patch_size (int): Size of patches to extract (default=128).

#     Returns:
#         X (np.ndarray): Input image patches, shape (N, patch_size, patch_size, C)
#         Y (np.ndarray): Mask patches, shape (N, patch_size, patch_size, 1)
#     """

#     X_list, Y_list = [], []

#     with h5py.File(hdf5_path, 'r') as f:
#         for key in f.keys():
#             region = f[key]

#             store_data = region.keys()

#             if "in_sar" not in store_data or "outlines" not in store_data:
#                 continue

#             insar_data = region["in_sar"]
#             outlines_data = region["outlines"]

#             # Feature and mask
#             img = np.array(insar_data)    # shape (H,W,C)
#             mask = np.array(outlines_data) # shape (H,W)

#             # Feature and mask
#             img = (img - np.min(img)) / (np.max(img) - np.min(img) + 1e-8)

#             # Convert mask to single channel (binary segmentation)
#             # If mask is one-hot encoded, this gives 0 for background, 1 for glacier
#             mask_single = np.argmax(mask, axis=-1).astype(np.float32)  # shape (H,W)

#             # Patchify
#             H, W = mask_single.shape
#             # create patches of 128*128
#             for i in range(0, H, patch_size):
#                 for j in range(0, W, patch_size):
#                     if i+patch_size <= H and j+patch_size <= W:
#                         patch_img = img[i:i+patch_size, j:j+patch_size, :]
#                         patch_mask = mask_single[i:i+patch_size, j:j+patch_size]
#                         X_list.append(patch_img)
#                         Y_list.append(patch_mask[..., np.newaxis])  # add channel axis

#     X = np.stack(X_list, axis=0)
#     Y = np.stack(Y_list, axis=0)

#     return X, Y

import numpy as np
import h5py

def process_hdf5_dataset(hdf5_path, patch_size=128):
    """
    Processes an InSAR HDF5 dataset into small patches for segmentation.
    Each region must contain 'in_sar' and 'outlines' datasets.

    Args:
        hdf5_path (str): Path to the HDF5 dataset.
        patch_size (int): Size of patches to extract (default=128).

    Returns:
        X (np.ndarray): Input image patches, shape (N, patch_size, patch_size, C)
        Y (np.ndarray): Mask patches, shape (N, patch_size, patch_size, 1)
    """
    X_list, Y_list = [], []
    region_count = 0  # To count valid regions with data

    with h5py.File(hdf5_path, 'r') as f:
        region_keys = [k for k in f.keys() if "in_sar" in f[k] and "outlines" in f[k]]
        for key in region_keys:
            region = f[key]

            # read arrays
            img = np.array(region["in_sar"])       # shape (H, W, C)
            mask = np.array(region["outlines"])    # shape (H, W, [classes])

            # normalize input to [0,1]
            img = (img - np.min(img)) / (np.max(img) - np.min(img) + 1e-8)

            # if mask is one-hot (H, W, 2) -> convert to binary (H, W)
            if mask.ndim == 3:
                mask = np.argmax(mask, axis=-1)

            mask = mask.astype(np.float32)
            H, W = mask.shape

            found_patch = False
            # extract non-overlapping patches
            for i in range(0, H - patch_size + 1, patch_size):
                for j in range(0, W - patch_size + 1, patch_size):
                    patch_img = img[i:i+patch_size, j:j+patch_size, :]
                    patch_mask = mask[i:i+patch_size, j:j+patch_size]

                    # skip empty patches (optional)
                    if np.sum(patch_mask) < 10:
                        continue

                    X_list.append(patch_img)
                    Y_list.append(patch_mask[..., np.newaxis])  # add channel
                    found_patch = True  # At least one patch found in this region

            if found_patch:
                region_count += 1

        # Print statement moved inside the 'with' block
        print(f"✅ Processed {len(X_list)} patches from {region_count} regions.")

    # stack into final numpy arrays (after file is closed)
    X = np.stack(X_list, axis=0)
    Y = np.stack(Y_list, axis=0)
    print(f"Final shapes -> X: {X.shape}, Y: {Y.shape}")

    return X, Y

# Usage
X, Y = process_hdf5_dataset(hdf5_path, patch_size=128)
print("Patches shape:", X.shape, Y.shape)

# # Split data into train, validation and testing

# X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, test_size=0.3, random_state=42)
# X_val, X_test, Y_val, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)
# print("Train:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

from sklearn.model_selection import train_test_split
import numpy as np

# Ensure data is shuffled consistently and reproducibly
X_train, X_temp, Y_train, Y_temp = train_test_split(
    X, Y, test_size=0.3, random_state=42, shuffle=True
)

# Split temp set into val and test (15% each)
X_val, X_test, Y_val, Y_test = train_test_split(
    X_temp, Y_temp, test_size=0.5, random_state=42, shuffle=True
)

print(f"✅ Data split successful:")
print(f"Train: {X_train.shape}")
print(f"Val:   {X_val.shape}")
print(f"Test:  {X_test.shape}")

# np.save("data/X_train.npy", X_train)
# np.save("data/Y_train.npy", Y_train)
# np.save("data/X_val.npy", X_val)
# np.save("data/Y_val.npy", Y_val)
# np.save("data/X_test.npy", X_test)
# np.save("data/Y_test.npy", Y_test)

# X_train = np.load("data/X_train.npy")
# Y_train = np.load("data/Y_train.npy")

import matplotlib.pyplot as plt
import random

# Randomly select an index from the training dataset
idx = random.randint(0, len(X_train)-1)

plt.figure(figsize=(12,4))

# Plot InSAR channel 1
plt.subplot(1,3,1)
plt.imshow(X_train[idx][:,:,0], cmap='gray')
plt.title("InSAR Channel 1")

# Plot InSAR channel 2
plt.subplot(1,3,2)
plt.imshow(X_train[idx][:,:,1], cmap='gray')
plt.title("InSAR Channel 2")

# Plot corresponding mask
plt.subplot(1,3,3)
plt.imshow(Y_train[idx].squeeze(), cmap='gray')
plt.title("Mask")

plt.tight_layout()
plt.show()

print(X_train[idx][:,:,0].min(), X_train[idx][:,:,0].max())
print(X_train[idx][:,:,1].min(), X_train[idx][:,:,1].max())

# !pip install torch torchvision torchaudio segmentation-models-pytorch torchmetrics scikit-learn matplotlib

"""## *BaseLine 'UNET' model (no denoising)*"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from torchmetrics.segmentation import DiceScore
from torchmetrics import JaccardIndex

# -----------------------------
# 1. Custom Dataset class: output tensors with correct shape (C,H,W)
# -----------------------------
class GlacierDataset(Dataset):
    def __init__(self, X, Y):
        # Ensure numpy arrays are float32 dtype and contiguous in memory
        self.X = np.ascontiguousarray(X.astype(np.float32))
        self.Y = np.ascontiguousarray(Y.astype(np.float32))

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        # Convert to torch tensors and permute dimensions from (H,W,C) to (C,H,W)
        img = torch.from_numpy(self.X[idx]).permute(2, 0, 1)
        mask = torch.from_numpy(self.Y[idx]).permute(2, 0, 1)
        return img, mask

train_dataset = GlacierDataset(X_train, Y_train)
val_dataset = GlacierDataset(X_val, Y_val)
test_dataset = GlacierDataset(X_test, Y_test)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

# Device selection: CUDA if available
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

# -----------------------------
#  Define pretrained U-Net model with ResNet34 backbone
# - Input channels are 2 for your InSAR data
# - Output classes 1 for binary segmentation (glacier vs non-glacier)
# - No activation here: sigmoid will be applied manually in loss and evaluation
# -----------------------------

model_unet = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",       # Use pretrained weights for robustness
    in_channels=X_train.shape[-1],    # Should be 2 based on your data shape (H,W,2)
    classes=1,
    activation=None
).to(DEVICE)

# -----------------------------
#  Dice Loss function definition for segmentation
# - Converts logits to probabilities internally
# - Dice coefficient is a good metric/loss for imbalanced segmentation classes
# -----------------------------

def dice_loss(pred, target, smooth=1e-6):
    pred = torch.sigmoid(pred)
    intersection = (pred * target).sum(dim=(2, 3))
    union = pred.sum(dim=(2, 3)) + target.sum(dim=(2, 3))
    dice = (2. * intersection + smooth) / (union + smooth)
    return 1 - dice.mean()

# -----------------------------
# Optimizer definition: Adam with learning rate 1e-4
# -----------------------------
optimizer = optim.Adam(model_unet.parameters(), lr=1e-4)

# -----------------------------
# Training loop over epochs
# - Tracks training loss and validation loss every epoch
# - Uses dice loss defined above
# -----------------------------

num_epochs = 150
for epoch in range(num_epochs):
    model_unet.train()  # Enable training model
    train_loss = 0.0

    for imgs, masks in train_loader:
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()
        outputs = model_unet(imgs)
        loss = dice_loss(outputs, masks)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    # Validation after each training epoch
    model_unet.eval()  # Set model to eval mode for validation
    val_loss = 0.0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            outputs = model_unet(imgs)
            loss = dice_loss(outputs, masks)
            val_loss += loss.item()

    # Print loss statistics for monitoring
    print(f"Epoch [{epoch+1}/{num_epochs}] | Train Loss: {train_loss/len(train_loader):.4f} | Val Loss: {val_loss/len(val_loader):.4f}")

# -----------------------------
#  Evaluate on test set after training completes
# - Computes Dice score and IoU (Jaccard Index) scores
# -----------------------------
model_unet.eval()

# Initialize Dice and IoU metrics for binary segmentation
dice_metric = DiceScore(num_classes=2, average='micro').to(DEVICE)
iou_metric = JaccardIndex(task="binary").to(DEVICE)

dice_scores, iou_scores = [], []


with torch.no_grad():
    for imgs, masks in DataLoader(test_dataset, batch_size=4):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        preds = torch.sigmoid(model_unet(imgs))
        preds_bin = (preds > 0.5).int()

        # Calculate Dice and IoU scores using the metric objects
        dice_score = dice_metric(preds_bin, masks.int())
        iou_score = iou_metric(preds_bin, masks.int())

        dice_scores.append(dice_score.item())
        iou_scores.append(iou_score.item())

print(f" Dice: {np.mean(dice_scores):.3f}")
print(f"  IoU:  {np.mean(iou_scores):.3f}")

# -----------------------------
# Save the trained model weights for future use
# -----------------------------
torch.save(model_unet.state_dict(), "unet_baseline.pth")
print("Model saved as unet_baseline.pth")

